### ISSUE TITLE
Need to know if this is available as a Chrome extension

### ISSUE THREAD

**Issue by yoyomonem** [NitroCipher/theme3#2]
Is this available on the Chrome Web Store? __I'm really excited to try it!__

**Comment by ZenithRogue** [comment]
Yes! This repository has been deprecated as an updated version is now available as part of [ScratchAddons](https://scratchaddons.com/)
![image](https://user-images.githubusercontent.com/11393734/194343205-eb91a7ad-7062-408f-a1fd-817b8cf963ea.png)

**Comment by yoyomonem** [comment]
> @ZenithRogue said:
>
> Yes! This repository has been deprecated as an updated version is now available as part of [Scratch Addons](https://scratchaddons.com/)
>
> ![image](https://user-images.githubusercontent.com/11393734/194343205-eb91a7ad-7062-408f-a1fd-817b8cf963ea.png)

Oh.
